<a href="https://colab.research.google.com/github/mirzulqarnain/DEEP_LEARNING_REPS/blob/main/Hyper_Parameter_Tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np
import pandas as pd

In [49]:
df = pd.read_csv('diabetes.csv')

In [50]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

As we have alot of inputs columns  we will check whicn inputs have affect the output or not so we use CORR function

In [51]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

now Extracting X and y values

In [52]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

Nowe we will scale our data

In [53]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [54]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [55]:
X = scaler.fit_transform(X)

In [56]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [57]:
X.shape

(768, 8)

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [111]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense ,Dropout

In [60]:
model = Sequential()
model.add(Dense(32,activation="relu",input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [61]:
model.fit(X_train,y_train, batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.5733 - loss: 0.6953 - val_accuracy: 0.6364 - val_loss: 0.6772
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6433 - loss: 0.6464 - val_accuracy: 0.6948 - val_loss: 0.6313
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.6096 - val_accuracy: 0.7403 - val_loss: 0.5958
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7085 - loss: 0.5830 - val_accuracy: 0.7532 - val_loss: 0.5683
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5601 - val_accuracy: 0.7792 - val_loss: 0.5474
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5418 - val_accuracy: 0.7792 - val_loss: 0.5275
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5265 - val_accuracy: 0.7792 - val_loss: 0.5132
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.5143 - val_accuracy: 0.7857 - val_loss: 0.5014
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.5037 - val_accuracy: 0.7922 - val_loss: 0.4914
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4955 - val_accuracy: 0.7922 - val_loss: 0.4845
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4882 - val_accuracy: 0.7987 - val_loss: 0.4784
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4824 - val_accuracy: 0.8052 - val_loss: 0.4742
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4775 - val_accuracy: 0.7987 - val_loss: 0.4704
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4737 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4700 - val_accuracy: 0.8052 - val_loss: 0.4657
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7736 - loss: 0.4673 - val_accuracy: 0.8052 - val_loss: 0.4638
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7720 - loss: 0.4642 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7769 - loss: 0.4618 - val_accuracy: 0.7987 - val_loss: 0.4614
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7818 - loss: 0.4603 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4586 - val_accuracy: 0.7987 - val_loss: 0.4588
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4570 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7818 - loss: 0.4558 - val_accuracy: 0.7922 - val_loss: 0.4580
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4555 - val_accuracy: 0.7857 - val_loss: 0.4573
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4543 - val_accuracy: 0.7922 - val_loss: 0.4565
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4529 - val_accuracy: 0.7922 - val_loss: 0.4558
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4520 - val_accuracy: 0.7922 - val_loss: 0.4565
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4508 - val_accuracy: 0.7922 - val_loss: 0.4557
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4502 - val_accuracy: 0.7857 - val_loss: 0.4547
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4490 - val_accuracy: 0.7792 - val_loss: 0.4560
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4485 - val_accuracy: 0.7792 - val_loss: 0.4563
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4472 - val_accuracy: 0.7857 - val_loss: 0.4570
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4464 - val_accuracy: 0.7792 - val_loss: 0.4577
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4453 - val_accuracy: 0.7792 - val_loss: 0.4579
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4449 - val_accuracy: 0.7792 - val_loss: 0.4575
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4440 - val_accuracy: 0.7792 - val_loss: 0.4591
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4433 - val_accuracy: 0.7792 - val_loss: 0.4583
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4426 - val_accuracy: 0.7857 - val_loss: 0.4572
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4420 - val_accuracy: 0.7857 - val_loss: 0.4572
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4412 - val_accuracy: 0.7857 - val_loss: 0.4576
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4408 - val_accuracy: 0.7857 - val_loss: 0.4578
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4400 - val_accuracy: 0.7857 - val_loss: 0.4587
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4395 - val_accuracy: 0.7857 - val_loss: 0.4596
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4389 - val_accuracy: 0.7922 - val_loss: 0.4601
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4386 - val_accuracy: 0.7857 - val_loss: 0.4603
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4381 - val_accuracy: 0.7857 - val_loss: 0.4600
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4375 - val_accuracy: 0.7857 - val_loss: 0.4595
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4365 - val_accuracy: 0.7857 - val_loss: 0.4590
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4366 - val_accuracy: 0.7922 - val_loss: 0.4583
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4360 - val_accuracy: 0.7922 - val_loss: 0.4587
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4360 - val_accuracy: 0.7857 - val_loss: 0.4600
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4352 - val_accuracy: 0.7922 - val_loss: 0.4591
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4346 - val_accuracy: 0.7857 - val_loss: 0.4592
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4341 - val_accuracy: 0.7857 - val_loss: 0.4590
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4337 - val_accuracy: 0.7857 - val_loss: 0.4583
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4332 - val_accuracy: 0.7922 - val_loss: 0.4590
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4325 - val_accuracy: 0.7922 - val_loss: 0.4589
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4328 - val_accuracy: 0.7987 - val_loss: 0.4590
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4322 - val_accuracy: 0.7922 - val_loss: 0.4609
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4308 - val_accuracy: 0.7922 - val_loss: 0.4595
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4304 - val_accuracy: 0.7987 - val_loss: 0.4586
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4305 - val_accuracy: 0.8052 - val_loss: 0.4575
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4298 - val_accuracy: 0.7857 - val_loss: 0.4573
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4293 - val_accuracy: 0.7987 - val_loss: 0.4568
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4291 - val_accuracy: 0.7987 - val_loss: 0.4560
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4286 - val_accuracy: 0.7857 - val_loss: 0.4574
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4280 - val_accuracy: 0.7857 - val_loss: 0.4568
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4273 - val_accuracy: 0.7922 - val_loss: 0.4579
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4272 - val_accuracy: 0.7922 - val_loss: 0.4570
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4269 - val_accuracy: 0.7922 - val_loss: 0.4579
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4261 - val_accuracy: 0.7987 - val_loss: 0.4577
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4258 - val_accuracy: 0.7922 - val_loss: 0.4586
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4257 - val_accuracy: 0.7922 - val_loss: 0.4594
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4251 - val_accuracy: 0.7922 - val_loss: 0.4585
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4244 - val_accuracy: 0.7922 - val_loss: 0.4580
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4247 - val_accuracy: 0.7922 - val_loss: 0.4579
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4238 - val_accuracy: 0.7922 - val_loss: 0.4569
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4235 - val_accuracy: 0.7922 - val_loss: 0.4577
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4233 - val_accuracy: 0.7987 - val_loss: 0.4582
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4230 - val_accuracy: 0.7987 - val_loss: 0.4578
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4221 - val_accuracy: 0.7987 - val_loss: 0.4580
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4223 - val_accuracy: 0.7922 - val_loss: 0.4570
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4217 - val_accuracy: 0.7987 - val_loss: 0.4559
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4212 - val_accuracy: 0.7987 - val_loss: 0.4560
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4216 - val_accuracy: 0.7987 - val_loss: 0.4556
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4210 - val_accuracy: 0.7987 - val_loss: 0.4556
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4204 - val_accuracy: 0.7987 - val_loss: 0.4561
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4202 - val_accuracy: 0.7922 - val_loss: 0.4569
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4196 - val_accuracy: 0.7987 - val_loss: 0.4563
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4195 - val_accuracy: 0.7987 - val_loss: 0.4559
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4187 - val_accuracy: 0.7987 - val_loss: 0.4548
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4185 - val_accuracy: 0.7987 - val_loss: 0.4567
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4186 - val_accuracy: 0.7987 - val_loss: 0.4565
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4183 - val_accuracy: 0.7987 - val_loss: 0.4558
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7932 - loss: 0.4178 - val_accuracy: 0.7987 - val_loss: 0.4570
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4182 - val_accuracy: 0.7922 - val_loss: 0.4563
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4177 - val_accuracy: 0.8052 - val_loss: 0.4572
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4176 - val_accuracy: 0.7987 - val_loss: 0.4561
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4175 - val_accuracy: 0.8117 - val_loss: 0.4574
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4163 - val_accuracy: 0.7987 - val_loss: 0.4572
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4161 - val_accuracy: 0.7987 - val_loss: 0.4563

In [ ]:
#1. how to select appropriate optimizer
#2. no. of nodes in a layer
#3. how to select no. of layers
#4. All in all one model

we will do all these things using a library named as kerastuner

In [62]:
pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.4.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [63]:
import keras_tuner as kt

In [64]:
def build_model(hp):

  model =  Sequential()

  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))
  optimizer=hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer=optimizer ,loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [65]:
tuner = kt.RandomSearch(build_model,
                       objective= 'val_accuracy',
                       max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [66]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [68]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
optimizer: adam
Score: 0.7727272510528564

Trial 2 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7662337422370911

Trial 3 summary
Hyperparameters:
optimizer: sgd
Score: 0.6623376607894897

Trial 1 summary
Hyperparameters:
optimizer: adadelta
Score: 0.3246753215789795

In [69]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [70]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [71]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [72]:
model.fit(X_train,y_train,batch_size =32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.7476 - loss: 0.5175 - val_accuracy: 0.7662 - val_loss: 0.5142
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5035 - val_accuracy: 0.7597 - val_loss: 0.5047
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4940 - val_accuracy: 0.7597 - val_loss: 0.4969
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.4865 - val_accuracy: 0.7727 - val_loss: 0.4912
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4802 - val_accuracy: 0.7727 - val_loss: 0.4854
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4754 - val_accuracy: 0.7727 - val_loss: 0.4809
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4709 - val_accuracy: 0.7792 - val_loss: 0.4812
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4687 - val_accuracy: 0.7727 - val_loss: 0.4776
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4655 - val_accuracy: 0.7727 - val_loss: 0.4758
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4623 - val_accuracy: 0.7727 - val_loss: 0.4732
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4606 - val_accuracy: 0.7727 - val_loss: 0.4714
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4586 - val_accuracy: 0.7727 - val_loss: 0.4707
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4566 - val_accuracy: 0.7662 - val_loss: 0.4707
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4548 - val_accuracy: 0.7662 - val_loss: 0.4711
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7720 - loss: 0.4536 - val_accuracy: 0.7727 - val_loss: 0.4703
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4525 - val_accuracy: 0.7727 - val_loss: 0.4709
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4513 - val_accuracy: 0.7857 - val_loss: 0.4699
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4500 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4490 - val_accuracy: 0.7857 - val_loss: 0.4686
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7720 - loss: 0.4478 - val_accuracy: 0.7727 - val_loss: 0.4691
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4472 - val_accuracy: 0.7727 - val_loss: 0.4670
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4465 - val_accuracy: 0.7792 - val_loss: 0.4683
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4449 - val_accuracy: 0.7922 - val_loss: 0.4660
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4447 - val_accuracy: 0.7857 - val_loss: 0.4650
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4438 - val_accuracy: 0.7857 - val_loss: 0.4644
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4427 - val_accuracy: 0.7792 - val_loss: 0.4643
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4422 - val_accuracy: 0.7922 - val_loss: 0.4638
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4417 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4411 - val_accuracy: 0.7922 - val_loss: 0.4627
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4405 - val_accuracy: 0.7922 - val_loss: 0.4623
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4406 - val_accuracy: 0.7857 - val_loss: 0.4655
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4393 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4385 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4381 - val_accuracy: 0.8052 - val_loss: 0.4618
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4375 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4372 - val_accuracy: 0.7987 - val_loss: 0.4612
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4359 - val_accuracy: 0.7987 - val_loss: 0.4610
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4360 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4353 - val_accuracy: 0.7857 - val_loss: 0.4596
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4352 - val_accuracy: 0.7987 - val_loss: 0.4597
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4346 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4341 - val_accuracy: 0.8052 - val_loss: 0.4593
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4336 - val_accuracy: 0.7987 - val_loss: 0.4597
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4335 - val_accuracy: 0.7987 - val_loss: 0.4597
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4327 - val_accuracy: 0.7987 - val_loss: 0.4595
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4323 - val_accuracy: 0.7987 - val_loss: 0.4586
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4325 - val_accuracy: 0.7987 - val_loss: 0.4585
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4316 - val_accuracy: 0.8052 - val_loss: 0.4579
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4312 - val_accuracy: 0.8052 - val_loss: 0.4588
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4305 - val_accuracy: 0.7987 - val_loss: 0.4606
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4310 - val_accuracy: 0.7922 - val_loss: 0.4607
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4302 - val_accuracy: 0.7987 - val_loss: 0.4603
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4296 - val_accuracy: 0.7987 - val_loss: 0.4603
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4293 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4289 - val_accuracy: 0.8052 - val_loss: 0.4579
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4284 - val_accuracy: 0.8117 - val_loss: 0.4573
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4286 - val_accuracy: 0.8182 - val_loss: 0.4567
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4281 - val_accuracy: 0.8117 - val_loss: 0.4565
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4277 - val_accuracy: 0.8117 - val_loss: 0.4548
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4280 - val_accuracy: 0.8052 - val_loss: 0.4548
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4269 - val_accuracy: 0.8182 - val_loss: 0.4561
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4267 - val_accuracy: 0.8182 - val_loss: 0.4543
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4274 - val_accuracy: 0.8182 - val_loss: 0.4542
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4261 - val_accuracy: 0.8182 - val_loss: 0.4546
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4258 - val_accuracy: 0.8182 - val_loss: 0.4523
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4254 - val_accuracy: 0.8052 - val_loss: 0.4528
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4248 - val_accuracy: 0.8247 - val_loss: 0.4525
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4247 - val_accuracy: 0.8182 - val_loss: 0.4532
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4247 - val_accuracy: 0.8052 - val_loss: 0.4531
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4240 - val_accuracy: 0.8247 - val_loss: 0.4532
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4239 - val_accuracy: 0.8182 - val_loss: 0.4533
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4238 - val_accuracy: 0.8117 - val_loss: 0.4542
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4233 - val_accuracy: 0.8117 - val_loss: 0.4543
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4227 - val_accuracy: 0.8182 - val_loss: 0.4530
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4224 - val_accuracy: 0.8182 - val_loss: 0.4526
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4225 - val_accuracy: 0.8182 - val_loss: 0.4535
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4218 - val_accuracy: 0.8182 - val_loss: 0.4528
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4221 - val_accuracy: 0.8117 - val_loss: 0.4512
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4212 - val_accuracy: 0.8117 - val_loss: 0.4521
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4210 - val_accuracy: 0.8182 - val_loss: 0.4535
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4206 - val_accuracy: 0.8247 - val_loss: 0.4510
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4200 - val_accuracy: 0.8182 - val_loss: 0.4514
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4201 - val_accuracy: 0.8247 - val_loss: 0.4508
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4197 - val_accuracy: 0.8247 - val_loss: 0.4521
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4195 - val_accuracy: 0.8182 - val_loss: 0.4512
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4190 - val_accuracy: 0.8182 - val_loss: 0.4514
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4187 - val_accuracy: 0.8182 - val_loss: 0.4513
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4181 - val_accuracy: 0.8247 - val_loss: 0.4514
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4181 - val_accuracy: 0.8247 - val_loss: 0.4514
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8078 - loss: 0.4178 - val_accuracy: 0.8247 - val_loss: 0.4529
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8078 - loss: 0.4180 - val_accuracy: 0.8247 - val_loss: 0.4534
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.4169 - val_accuracy: 0.8247 - val_loss: 0.4513
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8094 - loss: 0.4172 - val_accuracy: 0.8182 - val_loss: 0.4512
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.4167 - val_accuracy: 0.8182 - val_loss: 0.4527

Now we will find out number of neurons in a Particular layer

In [74]:
def build_model(hp):
  model = Sequential()
  units =  hp.Int('units',min_value=8,max_value = 128,step=8)

  model.add(Dense(units=units,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [79]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials=5,
                        directory='mydir',
                        project_name='nain')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [80]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.7597402334213257

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 21s

In [81]:
tuner.results_summary()

Results summary
Results in mydir/nain
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
units: 128
Score: 0.798701286315918

Trial 3 summary
Hyperparameters:
units: 96
Score: 0.7857142686843872

Trial 1 summary
Hyperparameters:
units: 48
Score: 0.7792207598686218

Trial 2 summary
Hyperparameters:
units: 40
Score: 0.7792207598686218

Trial 4 summary
Hyperparameters:
units: 24
Score: 0.7597402334213257

In [82]:
tuner.get_best_hyperparameters()[0].values

{'units': 128}

In [83]:
model= tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [84]:
model.fit(X_train,y_train,batch_size=100,initial_epoch=6)

seleting NO. of layers

In [94]:
def build_model(hp):

  model = Sequential()
  model.add(Dense(72,activation='relu',input_dim=8))
  for i in range (hp.Int('num_layers',min_value=1,max_value=10)):

    model.add(Dense(72,activation = 'relu'))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [95]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name= 'num_layers')

In [96]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 08s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.8376623392105103
Total elapsed time: 00h 00m 20s

In [97]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4}

In [98]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 26 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [104]:
model.fit(
    X_train,
    y_train,
    batch_size=100,
    initial_epoch=6,
    epochs=100,
    validation_data=(X_test,y_test),
    verbose=1
)

Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7997 - loss: 0.4238 - val_accuracy: 0.8182 - val_loss: 0.4399
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7899 - loss: 0.4273 - val_accuracy: 0.8182 - val_loss: 0.4372
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8013 - loss: 0.4192 - val_accuracy: 0.8117 - val_loss: 0.4396
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7997 - loss: 0.4066 - val_accuracy: 0.7922 - val_loss: 0.4514
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7948 - loss: 0.4130 - val_accuracy: 0.8052 - val_loss: 0.4335
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8094 - loss: 0.3999 - val_accuracy: 0.8247 - val_loss: 0.4273
Epoch 13/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8094 - loss: 0.3915 - val_accuracy: 0.8247 - val_loss: 0.4283
Epoch 14/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8160 - loss: 0.4059 - val_accuracy: 0.8247 - val_loss: 0.4286
Epoch 15/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8176 - loss: 0.3829 - val_accuracy: 0.7987 - val_loss: 0.4324
Epoch 16/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8160 - loss: 0.3805 - val_accuracy: 0.8182 - val_loss: 0.4337
Epoch 17/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8192 - loss: 0.3762 - val_accuracy: 0.8052 - val_loss: 0.4409
Epoch 18/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8290 - loss: 0.3689 - val_accuracy: 0.8052 - val_loss: 0.4423
Epoch 19/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8453 - loss: 0.3616 - val_accuracy: 0.8182 - val_loss: 0.4292
Epoch 20/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8306 - loss: 0.3611 - val_accuracy: 0.8247 - val_loss: 0.4345
Epoch 21/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8502 - loss: 0.3530 - val_accuracy: 0.7987 - val_loss: 0.4473
Epoch 22/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8583 - loss: 0.3394 - val_accuracy: 0.7857 - val_loss: 0.4581
Epoch 23/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8502 - loss: 0.3286 - val_accuracy: 0.7792 - val_loss: 0.4563
Epoch 24/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8518 - loss: 0.3367 - val_accuracy: 0.7987 - val_loss: 0.4924
Epoch 25/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8567 - loss: 0.3399 - val_accuracy: 0.7857 - val_loss: 0.4528
Epoch 26/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8616 - loss: 0.3178 - val_accuracy: 0.7922 - val_loss: 0.4589
Epoch 27/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8746 - loss: 0.3148 - val_accuracy: 0.7987 - val_loss: 0.4663
Epoch 28/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8713 - loss: 0.3097 - val_accuracy: 0.7727 - val_loss: 0.4692
Epoch 29/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8746 - loss: 0.3070 - val_accuracy: 0.7922 - val_loss: 0.4629
Epoch 30/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8811 - loss: 0.2885 - val_accuracy: 0.7987 - val_loss: 0.4570
Epoch 31/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8827 - loss: 0.2869 - val_accuracy: 0.7727 - val_loss: 0.4726
Epoch 32/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8925 - loss: 0.2718 - val_accuracy: 0.7922 - val_loss: 0.4930
Epoch 33/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8958 - loss: 0.2667 - val_accuracy: 0.7727 - val_loss: 0.4917
Epoch 34/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8925 - loss: 0.2634 - val_accuracy: 0.7792 - val_loss: 0.5031
Epoch 35/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8990 - loss: 0.2548 - val_accuracy: 0.7468 - val_loss: 0.5557
Epoch 36/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9072 - loss: 0.2451 - val_accuracy: 0.7727 - val_loss: 0.5190
Epoch 37/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9088 - loss: 0.2353 - val_accuracy: 0.7597 - val_loss: 0.5385
Epoch 38/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9202 - loss: 0.2214 - val_accuracy: 0.7727 - val_loss: 0.5615
Epoch 39/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9251 - loss: 0.2124 - val_accuracy: 0.7727 - val_loss: 0.5623
Epoch 40/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9300 - loss: 0.2061 - val_accuracy: 0.7403 - val_loss: 0.5834
Epoch 41/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9121 - loss: 0.2205 - val_accuracy: 0.7273 - val_loss: 0.6163
Epoch 42/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9104 - loss: 0.2161 - val_accuracy: 0.7403 - val_loss: 0.6035
Epoch 43/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9365 - loss: 0.1962 - val_accuracy: 0.7468 - val_loss: 0.6030
Epoch 44/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9381 - loss: 0.1856 - val_accuracy: 0.7143 - val_loss: 0.6323
Epoch 45/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9446 - loss: 0.1600 - val_accuracy: 0.7468 - val_loss: 0.6507
Epoch 46/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9349 - loss: 0.1753 - val_accuracy: 0.7143 - val_loss: 0.7579
Epoch 47/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9283 - loss: 0.1837 - val_accuracy: 0.7532 - val_loss: 0.6844
Epoch 48/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9381 - loss: 0.1610 - val_accuracy: 0.7403 - val_loss: 0.6975
Epoch 49/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9349 - loss: 0.1660 - val_accuracy: 0.7273 - val_loss: 0.7427
Epoch 50/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9544 - loss: 0.1431 - val_accuracy: 0.7338 - val_loss: 0.6989
Epoch 51/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9528 - loss: 0.1317 - val_accuracy: 0.7208 - val_loss: 0.7457
Epoch 52/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9642 - loss: 0.1129 - val_accuracy: 0.7143 - val_loss: 0.8123
Epoch 53/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9446 - loss: 0.1360 - val_accuracy: 0.7078 - val_loss: 0.8362
Epoch 54/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9511 - loss: 0.1341 - val_accuracy: 0.7273 - val_loss: 0.9499
Epoch 55/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9023 - loss: 0.2063 - val_accuracy: 0.7532 - val_loss: 0.9495
Epoch 56/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9397 - loss: 0.1493 - val_accuracy: 0.7338 - val_loss: 0.8072
Epoch 57/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9691 - loss: 0.1049 - val_accuracy: 0.7013 - val_loss: 0.8972
Epoch 58/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9674 - loss: 0.0992 - val_accuracy: 0.7208 - val_loss: 0.8831
Epoch 59/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9723 - loss: 0.0927 - val_accuracy: 0.7273 - val_loss: 0.8853
Epoch 60/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9756 - loss: 0.0902 - val_accuracy: 0.7078 - val_loss: 0.9498
Epoch 61/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9691 - loss: 0.0953 - val_accuracy: 0.7403 - val_loss: 0.9374
Epoch 62/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9609 - loss: 0.0961 - val_accuracy: 0.7403 - val_loss: 1.0655
Epoch 63/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9723 - loss: 0.0828 - val_accuracy: 0.7662 - val_loss: 0.9339
Epoch 64/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9756 - loss: 0.0711 - val_accuracy: 0.7078 - val_loss: 0.9630
Epoch 65/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9919 - loss: 0.0536 - val_accuracy: 0.7273 - val_loss: 1.0482
Epoch 66/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9821 - loss: 0.0556 - val_accuracy: 0.7468 - val_loss: 1.0286
Epoch 67/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9886 - loss: 0.0488 - val_accuracy: 0.7078 - val_loss: 1.1070
Epoch 68/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9951 - loss: 0.0435 - val_accuracy: 0.7338 - val_loss: 1.1142
Epoch 69/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9886 - loss: 0.0555 - val_accuracy: 0.7208 - val_loss: 1.1732
Epoch 70/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9756 - loss: 0.0643 - val_accuracy: 0.7078 - val_loss: 1.2178
Epoch 71/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9821 - loss: 0.0525 - val_accuracy: 0.7273 - val_loss: 1.1573
Epoch 72/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9837 - loss: 0.0602 - val_accuracy: 0.7208 - val_loss: 1.2520
Epoch 73/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9853 - loss: 0.0399 - val_accuracy: 0.7143 - val_loss: 1.1897
Epoch 74/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9886 - loss: 0.0385 - val_accuracy: 0.7078 - val_loss: 1.3139
Epoch 75/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9902 - loss: 0.0439 - val_accuracy: 0.7078 - val_loss: 1.2889
Epoch 76/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9902 - loss: 0.0491 - val_accuracy: 0.6948 - val_loss: 1.3248
Epoch 77/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9886 - loss: 0.0375 - val_accuracy: 0.6948 - val_loss: 1.4320
Epoch 78/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9870 - loss: 0.0411 - val_accuracy: 0.6883 - val_loss: 1.3184
Epoch 79/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9984 - loss: 0.0243 - val_accuracy: 0.7013 - val_loss: 1.4220
Epoch 80/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9935 - loss: 0.0296 - val_accuracy: 0.7208 - val_loss: 1.3824
Epoch 81/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9951 - loss: 0.0254 - val_accuracy: 0.7013 - val_loss: 1.5464
Epoch 82/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9951 - loss: 0.0229 - val_accuracy: 0.7013 - val_loss: 1.4509
Epoch 83/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0143 - val_accuracy: 0.6948 - val_loss: 1.5341
Epoch 84/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0147 - val_accuracy: 0.7078 - val_loss: 1.5065
Epoch 85/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0129 - val_accuracy: 0.7013 - val_loss: 1.5991
Epoch 86/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9984 - loss: 0.0128 - val_accuracy: 0.7013 - val_loss: 1.5562
Epoch 87/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9984 - loss: 0.0113 - val_accuracy: 0.7078 - val_loss: 1.6047
Epoch 88/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9984 - loss: 0.0114 - val_accuracy: 0.7013 - val_loss: 1.6091
Epoch 89/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0089 - val_accuracy: 0.7013 - val_loss: 1.6407
Epoch 90/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9984 - loss: 0.0086 - val_accuracy: 0.6948 - val_loss: 1.6906
Epoch 91/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0074 - val_accuracy: 0.6948 - val_loss: 1.6946
Epoch 92/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0070 - val_accuracy: 0.6883 - val_loss: 1.7566
Epoch 93/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0071 - val_accuracy: 0.6883 - val_loss: 1.7518
Epoch 94/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0062 - val_accuracy: 0.6883 - val_loss: 1.7843
Epoch 95/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9984 - loss: 0.0071 - val_accuracy: 0.7013 - val_loss: 1.7793
Epoch 96/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9984 - loss: 0.0074 - val_accuracy: 0.6948 - val_loss: 1.8027
Epoch 97/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9984 - loss: 0.0091 - val_accuracy: 0.7013 - val_loss: 1.8072
Epoch 98/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9984 - loss: 0.0070 - val_accuracy: 0.6948 - val_loss: 1.8240
Epoch 99/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9984 - loss: 0.0052 - val_accuracy: 0.6948 - val_loss: 1.8629
Epoch 100/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.6883 - val_loss: 1.8563

In [112]:
def build_model(hp):

    model = Sequential()

    counter = 0

    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):

        if counter == 0:

            model.add(
                Dense(
                    hp.Int(
                        'units' + str(i),
                        min_value=8,
                        max_value=128,
                        step=8
                    ),
                    activation=hp.Choice(
                        'activation' + str(i),
                        values=['relu', 'tanh', 'sigmoid']
                    ),
                    input_dim=8
                )
            )

            model.add(
                Dropout(
                    hp.Choice(
                        'dropout' + str(i),
                        values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
                    )
                )
            )

        else:

            model.add(
                Dense(
                    hp.Int(
                        'units' + str(i),
                        min_value=8,
                        max_value=128,
                        step=8
                    ),
                    activation=hp.Choice(
                        'activation' + str(i),
                        values=['relu', 'tanh', 'sigmoid']
                    )
                )
            )

            model.add(
                Dropout(
                    hp.Choice(
                        'dropout' + str(i),
                        values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
                    )
                )
            )

        counter += 1

    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer=hp.Choice(
            'optimizer',
            values=['adam', 'sgd', 'rmsprop', 'adadelta']
        ),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [113]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='final')

Reloading Tuner from mydir/final/tuner0.json

In [114]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [115]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4,
 'units0': 48,
 'activation0': 'sigmoid',
 'optimizer': 'adam',
 'units1': 104,
 'activation1': 'relu',
 'units2': 96,
 'activation2': 'tanh',
 'units3': 88,
 'activation3': 'sigmoid'}

In [109]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [116]:
model.fit(X_train,y_train,epochs=200,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8550 - loss: 0.3334 - val_accuracy: 0.7662 - val_loss: 0.5226
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3514 - val_accuracy: 0.7792 - val_loss: 0.5009
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3286 - val_accuracy: 0.7597 - val_loss: 0.5424
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8420 - loss: 0.3344 - val_accuracy: 0.7727 - val_loss: 0.5217
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3130 - val_accuracy: 0.7922 - val_loss: 0.5184
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3251 - val_accuracy: 0.7597 - val_loss: 0.5303
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3216 - val_accuracy: 0.7597 - val_loss: 0.5389
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3143 - val_accuracy: 0.7727 - val_loss: 0.5324
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3093 - val_accuracy: 0.7662 - val_loss: 0.5371
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3118 - val_accuracy: 0.7532 - val_loss: 0.5427
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3085 - val_accuracy: 0.7532 - val_loss: 0.5387
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3102 - val_accuracy: 0.7727 - val_loss: 0.5438
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3366 - val_accuracy: 0.7403 - val_loss: 0.5724
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3145 - val_accuracy: 0.7597 - val_loss: 0.5386
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3052 - val_accuracy: 0.7597 - val_loss: 0.5491
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3122 - val_accuracy: 0.7468 - val_loss: 0.5439
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.2959 - val_accuracy: 0.7597 - val_loss: 0.5486
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.2901 - val_accuracy: 0.7727 - val_loss: 0.5569
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.2937 - val_accuracy: 0.7403 - val_loss: 0.5569
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3071 - val_accuracy: 0.7662 - val_loss: 0.5406
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3047 - val_accuracy: 0.7597 - val_loss: 0.5607
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.2932 - val_accuracy: 0.7273 - val_loss: 0.5670
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.2949 - val_accuracy: 0.7532 - val_loss: 0.5921
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3108 - val_accuracy: 0.7727 - val_loss: 0.5430
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.2939 - val_accuracy: 0.7338 - val_loss: 0.5540
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.2744 - val_accuracy: 0.7662 - val_loss: 0.5679
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3009 - val_accuracy: 0.7208 - val_loss: 0.6409
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3027 - val_accuracy: 0.7662 - val_loss: 0.5555
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3048 - val_accuracy: 0.7403 - val_loss: 0.5925
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2954 - val_accuracy: 0.7403 - val_loss: 0.5713
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2831 - val_accuracy: 0.7662 - val_loss: 0.5742
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.2753 - val_accuracy: 0.7403 - val_loss: 0.5991
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.2792 - val_accuracy: 0.7273 - val_loss: 0.5981
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2956 - val_accuracy: 0.7013 - val_loss: 0.6614
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3001 - val_accuracy: 0.7078 - val_loss: 0.6051
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.2723 - val_accuracy: 0.7273 - val_loss: 0.6201
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.2636 - val_accuracy: 0.7403 - val_loss: 0.6273
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.2771 - val_accuracy: 0.7403 - val_loss: 0.5651
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.2790 - val_accuracy: 0.7597 - val_loss: 0.6026
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.2748 - val_accuracy: 0.7208 - val_loss: 0.6308
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.2760 - val_accuracy: 0.7273 - val_loss: 0.6282
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2697 - val_accuracy: 0.7857 - val_loss: 0.6049
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.2723 - val_accuracy: 0.7468 - val_loss: 0.6109
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.2938 - val_accuracy: 0.7338 - val_loss: 0.5795
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2781 - val_accuracy: 0.7273 - val_loss: 0.6447
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3307 - val_accuracy: 0.7208 - val_loss: 0.6302
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3220 - val_accuracy: 0.7403 - val_loss: 0.5704
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.2814 - val_accuracy: 0.7338 - val_loss: 0.6124
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2640 - val_accuracy: 0.7078 - val_loss: 0.6894
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2675 - val_accuracy: 0.7727 - val_loss: 0.5892
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2713 - val_accuracy: 0.7662 - val_loss: 0.6048
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2694 - val_accuracy: 0.7468 - val_loss: 0.6474
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2585 - val_accuracy: 0.7662 - val_loss: 0.5994
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2434 - val_accuracy: 0.7403 - val_loss: 0.6421
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9039 - loss: 0.2454 - val_accuracy: 0.7403 - val_loss: 0.6607
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2361 - val_accuracy: 0.7532 - val_loss: 0.6839
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2486 - val_accuracy: 0.7078 - val_loss: 0.7201
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2418 - val_accuracy: 0.7403 - val_loss: 0.6852
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2416 - val_accuracy: 0.7662 - val_loss: 0.6890
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9039 - loss: 0.2444 - val_accuracy: 0.7597 - val_loss: 0.7004
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2515 - val_accuracy: 0.7403 - val_loss: 0.6561
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2347 - val_accuracy: 0.7597 - val_loss: 0.6602
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2463 - val_accuracy: 0.7532 - val_loss: 0.7193
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2393 - val_accuracy: 0.7597 - val_loss: 0.6618
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2332 - val_accuracy: 0.7143 - val_loss: 0.7517
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8730 - loss: 0.2818 - val_accuracy: 0.7208 - val_loss: 0.7664
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8746 - loss: 0.3056 - val_accuracy: 0.7468 - val_loss: 0.7238
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8844 - loss: 0.2763 - val_accuracy: 0.7532 - val_loss: 0.6467
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8909 - loss: 0.2669 - val_accuracy: 0.7273 - val_loss: 0.7358
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9153 - loss: 0.2425 - val_accuracy: 0.7338 - val_loss: 0.6775
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9088 - loss: 0.2262 - val_accuracy: 0.7468 - val_loss: 0.6779
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9153 - loss: 0.2175 - val_accuracy: 0.7662 - val_loss: 0.6438
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9153 - loss: 0.2240 - val_accuracy: 0.7662 - val_loss: 0.6826
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8990 - loss: 0.2421 - val_accuracy: 0.7597 - val_loss: 0.6638
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8990 - loss: 0.2448 - val_accuracy: 0.6883 - val_loss: 0.7275
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2416 - val_accuracy: 0.7273 - val_loss: 0.7040
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2576 - val_accuracy: 0.7468 - val_loss: 0.6264
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2524 - val_accuracy: 0.7208 - val_loss: 0.7590
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2419 - val_accuracy: 0.7597 - val_loss: 0.6495
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9137 - loss: 0.2179 - val_accuracy: 0.6948 - val_loss: 0.7530
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2298 - val_accuracy: 0.7403 - val_loss: 0.6519
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2289 - val_accuracy: 0.7597 - val_loss: 0.6815
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9088 - loss: 0.2217 - val_accuracy: 0.7078 - val_loss: 0.7565
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2141 - val_accuracy: 0.7662 - val_loss: 0.6759
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9186 - loss: 0.2129 - val_accuracy: 0.7532 - val_loss: 0.6993
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2402 - val_accuracy: 0.7468 - val_loss: 0.7370
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2467 - val_accuracy: 0.7403 - val_loss: 0.7315
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2404 - val_accuracy: 0.7273 - val_loss: 0.7071
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9267 - loss: 0.2029 - val_accuracy: 0.7273 - val_loss: 0.7165
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2256 - val_accuracy: 0.7273 - val_loss: 0.7569
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.2973 - val_accuracy: 0.7338 - val_loss: 0.8142
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2424 - val_accuracy: 0.7338 - val_loss: 0.6485
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2472 - val_accuracy: 0.7597 - val_loss: 0.6789
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2482 - val_accuracy: 0.7792 - val_loss: 0.6375
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2383 - val_accuracy: 0.7338 - val_loss: 0.7097
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9039 - loss: 0.2373 - val_accuracy: 0.7597 - val_loss: 0.7590
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2332 - val_accuracy: 0.7338 - val_loss: 0.8117
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2423 - val_accuracy: 0.7143 - val_loss: 0.7535
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2177 - val_accuracy: 0.7078 - val_loss: 0.7964
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9251 - loss: 0.2097 - val_accuracy: 0.7468 - val_loss: 0.6908
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9202 - loss: 0.1981 - val_accuracy: 0.7273 - val_loss: 0.7964
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1987 - val_accuracy: 0.7468 - val_loss: 0.6952
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9202 - loss: 0.1944 - val_accuracy: 0.7273 - val_loss: 0.7980
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2149 - val_accuracy: 0.7013 - val_loss: 0.7851
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2349 - val_accuracy: 0.7727 - val_loss: 0.6870
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9186 - loss: 0.2157 - val_accuracy: 0.7597 - val_loss: 0.6745
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1987 - val_accuracy: 0.7468 - val_loss: 0.7336
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2122 - val_accuracy: 0.7597 - val_loss: 0.7484
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2443 - val_accuracy: 0.7597 - val_loss: 0.7107
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9169 - loss: 0.2371 - val_accuracy: 0.7597 - val_loss: 0.6664
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2965 - val_accuracy: 0.7662 - val_loss: 0.6599
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2301 - val_accuracy: 0.7208 - val_loss: 0.6874
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2211 - val_accuracy: 0.7468 - val_loss: 0.6864
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9235 - loss: 0.2201 - val_accuracy: 0.7597 - val_loss: 0.6285
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2300 - val_accuracy: 0.7208 - val_loss: 0.7005
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9218 - loss: 0.2042 - val_accuracy: 0.7597 - val_loss: 0.6780
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9283 - loss: 0.2025 - val_accuracy: 0.7338 - val_loss: 0.7267
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9218 - loss: 0.1978 - val_accuracy: 0.7597 - val_loss: 0.7215
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9202 - loss: 0.2018 - val_accuracy: 0.7338 - val_loss: 0.7238
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1847 - val_accuracy: 0.7208 - val_loss: 0.7563
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9365 - loss: 0.1859 - val_accuracy: 0.7662 - val_loss: 0.6951
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1804 - val_accuracy: 0.7338 - val_loss: 0.7709
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1743 - val_accuracy: 0.7468 - val_loss: 0.7539
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2553 - val_accuracy: 0.7792 - val_loss: 0.7397
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9235 - loss: 0.2117 - val_accuracy: 0.7403 - val_loss: 0.6879
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.2080 - val_accuracy: 0.7338 - val_loss: 0.8581
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2093 - val_accuracy: 0.7208 - val_loss: 0.7285
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1914 - val_accuracy: 0.7532 - val_loss: 0.7377
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1865 - val_accuracy: 0.7403 - val_loss: 0.7513
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1682 - val_accuracy: 0.7338 - val_loss: 0.7527
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9332 - loss: 0.1862 - val_accuracy: 0.7532 - val_loss: 0.7602
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9218 - loss: 0.1927 - val_accuracy: 0.7532 - val_loss: 0.7422
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1878 - val_accuracy: 0.7468 - val_loss: 0.8152
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9332 - loss: 0.1723 - val_accuracy: 0.7273 - val_loss: 0.7838
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9186 - loss: 0.1899 - val_accuracy: 0.7727 - val_loss: 0.7505
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9235 - loss: 0.1895 - val_accuracy: 0.7597 - val_loss: 0.7794
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9267 - loss: 0.1784 - val_accuracy: 0.7273 - val_loss: 0.8232
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9218 - loss: 0.1917 - val_accuracy: 0.7468 - val_loss: 0.8324
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9218 - loss: 0.1894 - val_accuracy: 0.7273 - val_loss: 0.8129
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1781 - val_accuracy: 0.7532 - val_loss: 0.7235
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9332 - loss: 0.1813 - val_accuracy: 0.7662 - val_loss: 0.7382
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9218 - loss: 0.2055 - val_accuracy: 0.7143 - val_loss: 0.8013
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9300 - loss: 0.2004 - val_accuracy: 0.7338 - val_loss: 0.8282
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9235 - loss: 0.2072 - val_accuracy: 0.7403 - val_loss: 0.8074
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9218 - loss: 0.2043 - val_accuracy: 0.7208 - val_loss: 0.8603
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9218 - loss: 0.1952 - val_accuracy: 0.7208 - val_loss: 0.7392
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9316 - loss: 0.1869 - val_accuracy: 0.7273 - val_loss: 0.8010
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9235 - loss: 0.1906 - val_accuracy: 0.7532 - val_loss: 0.7315
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9430 - loss: 0.1677 - val_accuracy: 0.7208 - val_loss: 0.8235
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9218 - loss: 0.1918 - val_accuracy: 0.7208 - val_loss: 0.8759
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9414 - loss: 0.1634 - val_accuracy: 0.7468 - val_loss: 0.7730
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9463 - loss: 0.1677 - val_accuracy: 0.7532 - val_loss: 0.8243
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.1946 - val_accuracy: 0.7273 - val_loss: 0.7927
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9365 - loss: 0.1840 - val_accuracy: 0.7662 - val_loss: 0.7708
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1688 - val_accuracy: 0.7403 - val_loss: 0.7824
Epoch 162/200